env_name       = "dev"
instance_type  = "t3.micro"
db_name        = "devdb"
db_username    = "postgres"
db_password    = "devpass123"
db_identifier  = "dev-db-2"
bucket_name    = "my-bucket-dev-cquinchiar"
aws_region     = "us-east-1"
