name: CI/CD with Terraform and EC2 Deployment

on:
  push:
    branches:
      - development
  workflow_dispatch:
    inputs:
      environment:
        description: "Ambiente (dev, test, prod)"
        required: true
        default: "dev"

jobs:
  build-and-deploy:
    name: Build Docker Image and Deploy to EC2
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:14
        env:
          POSTGRES_DB: mydb
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U user -d mydb"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r app/requirements.txt

      - name: Run lint
        run: flake8 app/

      - name: Esperar a que PostgreSQL esté listo
        run: |
          for i in {1..10}; do
            pg_isready -h localhost -U user -d mydb && break
            echo "Esperando a PostgreSQL..."
            sleep 3
          done
        env:
          PGPASSWORD: password

      - name: Run tests
        run: DB_HOST=localhost pytest app/

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/flask-app:latest

      
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ env.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            if [ ! -d "flask-app" ]; then
              git clone https://github.com/cristianquin/CI-CD.git flask-app
            fi
            cd flask-app
            git pull origin development
            docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker pull cristianquin/flask-app:latest
            docker-compose down
            docker-compose up -d

