name: Terraform Apply

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: "Ambiente (dev, test, prod)"
        required: true
        default: "dev"

jobs:
  terraform-apply:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve -var-file="environments/${{ github.event.inputs.environment }}.tfvars"
